config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :brands
	resources :equipments
	resources :customers
	resources :orders

	root to: 'orders#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Azordens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/assets/angular-i18n/angular-locale_pt-br.js"></script>
  </head>

  <body ng-controller="MainCtrl">

    <div id="wrapper">
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header w-100">
          <%= link_to orders_path, class: "navbar-brand" do %>
            <%= image_tag 'logo.png', class: 'img-responsive w-200' %>
          <% end %>

          <%= button_to destroy_user_session_path, class: 'btn btn-danger m-t-8 m-r-15 relative pull-right', :method => :delete, data: {confirm: 'Sair?'} do %>
            <i class="fa fa-power-off"></i>
          <% end %>

          <button type="button" ng-click="showHints(true)" class="btn btn-primary btn-circle m-t-8 m-r-10 relative pull-right">
            <i class="fa fa-question"></i>
          </button>

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

      </nav>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
            <%= link_to orders_path, class: is_active('orders') do %>
              <i class="fa fa-fw fa-sticky-note-o"></i> Ordens de serviço
            <% end %>
          </li>
          <li>
            <%= link_to customers_path, class: is_active('customers') do %>
              <i class="fa fa-fw fa-users"></i> Clientes
            <% end %>
          </li>
          <li>
            <%= link_to equipments_path, class: is_active('equipments') do %>
              <i class="fa fa-fw fa-wrench"></i> Equipamentos
            <% end %>
          </li>
          <li>
            <%= link_to brands_path, class: is_active('brands') do %>
              <i class="fa fa-fw fa-heart"></i> Marcas
            <% end %>
          </li>
        </ul>
      </div>

      <div id="page-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
      {{showHints(false)}}
	  </div>
  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Azordens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/assets/angular-i18n/angular-locale_pt-br.js"></script>
  </head>

  <body class="sessions" ng-controller="MainCtrl">

    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4 bgm-white p-30">
          <%= image_tag 'logo.png', class: 'img-responsive' %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4 col-xs-offset-4 bgm-white">
          <% flash.each do |key, msg| %>
            <div class="alert alert-warning">
              <a href="#" data-dismiss="alert" class="close">×</a>
                <p><i class="fa fa-info-circle"></i> <%= msg %></p>
            </div>
          <% end %>
          <% if devise_error_messages!.any? %>
            <div class="alert alert-warning">
              <a href="#" data-dismiss="alert" class="close">×</a>
              <% devise_error_messages!.each do |msg| %>
                <p><i class="fa fa-info-circle"></i> <%= msg %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6 col-xs-offset-4">
          <%= yield %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 force-to-bottom text-right c-white">
        Criado por <a target="_blank" href="https://www.facebook.com/zordanguilherme">Guilherme</a> <a target="_blank" href="https://www.linkedin.com/profile/view?id=AAMAABjhGysBYDFpD-63zHCC3GO0HLxYQJ2XHms&trk=hp-identity-photo">Zordan</a>
      </div>
    </div>
  </body>

</html>